


sometarget:
	@ echo no active target

picocoma:
	@./cf-fastpico9t /dev/ttyACM0

picocomb:
	@./cf-fastpico9t /dev/ttyACM1

picocom:	picocoma

notes:
	@echo 'wrt the reading word:'
	@echo 'COLD reading ESC .S   is functional outside vscode'
	@echo ' '
	@echo 'the .S word will reflect an address on TOS'

