# Fri 22 Nov 16:31:33 UTC 2024
# was: Fri 22 Nov 15:20:11 UTC 2024
# was: Sun 17 Nov 22:13:43 UTC 2024

SHELL = /bin/sh

# FOR HINTS please see this critically important file:
#   camelforth-rp2350-a-MS-U/17-camelforth-b.d/pico-examples/build_pico2/CMakeFiles/Makefile2

# - - - locally specified stuff - - -

SHRED=--prev_built--2297-bb

all:	allnvb

allvb:	make_j4_verbs ending

allnvb:	make_j4 ending

git_status:
	@git status | cat | tr -d '\t'

pwd:
	@echo -n '  ..'
	@pwd | cut -b 27-

pid_standin := $(shell date +%d.%H.%M.%S)
pid_standin_short := $(shell date +%d.%H)

dir_setups:	.begin
	@if [ -d "./build_pico2" ]; \
		then mv ./build_pico2 ./build_pico2-${SHRED}-${pid_standin}- ; \
		ls -1 ./build_pico2-${SHRED}-${pid_standin_short}* ; \
	fi
	@date ; echo -n 'sleeping 1 second..' ; sleep 1; echo '.  Done.' ; sleep 1
	@mkdir ./build_pico2 ; date > ./build_pico2/.semaphore-${pid_standin}-
	@sha1sum ./build_pico2/.semaphore-${pid_standin}-

cmaking:	dir_setups
	@cd ./build_pico2 ; cmake ../ -DPICO_BOARD=pico2 \
	-DCMAKE_BUILD_TYPE=Debug ; date > carson.loud.mi.ti

make_j4_verbs:	cmaking
	@cd ./build_pico2/camelforth-b ; make -j4 VERBOSE=1

make_j4:	cmaking
	@cd ./build_pico2/camelforth-b ; make -j4

just_the_cma:
	@cmake ../ -DPICO_BOARD=pico2 -DCMAKE_BUILD_TYPE=Debug

dirs_to_mv = $(wildcard ./build_pico2---prev_buil*)

# echo; echo " \044 pwd \c" ; pwd ; echo   # the \c says print no more output.

_cleaner:
	@echo these previous build directories are to be moved to the trash directory:
	@date; echo -n '  sleeping for 1 second..' ; sleep 1; echo '.  Done.' ; sleep 1
	@echo $(dirs_to_mv)
	@cd ./nbuild--rescind/trash.d ; \
		for indexed in $(dirs_to_mv) ; \
		do mv ../../$$indexed  . ; \
		echo; echo " \044 pwd" ; pwd ; echo ; \
		echo " \044 lsd" ; lsd ; \
		date ; sleep 1; done
	@echo cleaned.

clean:	.clean _cleaner ending

ending:	.end


# ---- messages ----

esc_char:
	@echo -n \\033

.end:
	@echo -e '\033\033[0;1;34m[\033[0;33mend.\033[0m\033[0;1;34m]\033[0m'

.begin:
	@echo -e '\033[0;1;34m[\033[0;33mbegin..\033[0m\033[0;1;34m]\033[0m'

.compile_non_verbose:
	@echo -e '\033[0;1;34m[\033[0;33mcompile non-verbose\033[0m\033[0;1;34m]\033[0m'

.clean:
	@echo -e '\033[0;1;34m[\033[0;33mclean\033[0m\033[0;1;34m]\033[0m'

.distclean:
	@echo -e '\033[0;1;34m[\033[0;33mdistclean\033[0m\033[0;1;34m]\033[0m'
	@> .semaphore-distclean

# end.

